# general makefile for simple C programs
# always links math.h, silent output w/ all errors which are useful, always enable debugger
# sends the binary to PATH with the generalized executable name [main]

default:
	@gcc main.c -lm -Wall -Wextra -Wpedantic -Wshadow -Wconversion -g -o ~/.local/bin/main
