#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# disable dpms and prevents screen from blanking
xset s off -dpms
# switch caps with escape
setxkbmap -option caps:escape

# screen compositor
picom -b &
# hide cursor
unclutter &
# polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# a window manager
exec awesome
